
version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/php:8.2
    volumes:
      - ..:/roots/app
    ports:
      - "8080:80"
    environment:
      - WP_ENV=development
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
